add github-actions
gcarreno/blink-my-duino pull request #2
Opened 2024-11-06 14:01 UTC by theavege

<b>Hello!</b>

Thanks for your project. I add github-actions. I hope it is useful.

<i>Thanks.</i>

2024-11-06 18:59 UTC, pascalecu requested changes

2024-11-06 18:59 UTC, pascalecu commented on make.ps1
Why have this when the sh file works?
Also:
- this doesn't respect most Powershell style guides (e.g. `PrivClipper` would be `Show-Usage`, `PrivMsiexec` would be `Install-MsiexecPackage` etc.), and also weird camel case identifiers that would be instantly formatted away
- it doesn't use the help system
- it doesn't validate anything
- the functions don't take any arguments whatsoever (cmon, this isn't Bash)
- you fail to take into consideration any time this will fail (no try/catch in sight, you like to live life dangerously)
- you can just use `&` instead of Start-Process, you know? `& git submodule update --recursive --init` reads much better than the eldritch horror you have with Start-Process
- Invoke-ScriptAnalyzer can throw an exception, but you don't even consider exceptions
- why not have a function that invokes lazbuild on a single package and use that? You are duplicating a lot of work
- finally... the first line is so ridiculous... how do you expect that Unix shebang to ever work on Windows? it defeats the whole point of this script... at that point you might as well assume WSL and use bash everywhere.

2024-11-06 18:59 UTC, pascalecu commented on make.sh
> +    if ! (which lazbuild); then
You should use `command -v lazbuild &>/dev/null`, it's more portable.

2024-11-06 18:59 UTC, pascalecu commented on make.sh
> +            if ! (lazbuild --verbose-pkgsearch "${REPLY}"); then
I don't know what you tried to do here, but the following is a much, MUCH cleaner of dealing with this:
```bash
while IFS= read -r component || [[ -n "$component" ]]; do
    if [[ -z "$component" ]]; then continue; fi
    echo "Checking package: $component"

    if ! lazbuild --verbose-pkgsearch "${component}" &>/dev/null; then
        if ! lazbuild --add-package "${component}" &>/dev/null; then
            component_dir="use/${component}"
            if [[ ! -d "$component_dir" ]]; then
                temp_zip=$(mktemp)
                component_url="https://packages.lazarus-ide.org/${component}.zip"
                echo "Downloading $component from $component_url..."
                wget -q --output-document "$temp_zip" "$component_url"

                echo "Extracting $component..."
                unzip -o "$temp_zip" -d "$component_dir"
                rm -v "$temp_zip"
            fi
        fi
    fi
done < 'use/components.txt'
```

2024-11-06 18:59 UTC, pascalecu commented on make.sh
> +        -exec lazbuild --no-write-project --recursive --no-write-project --build-mode=release {} + 1>&2
I am not quite sure why you need to have `1>&2` here, but `-type` doesn't take its arguments as strings, so you need to write `-type f`.

2024-11-06 18:59 UTC, pascalecu commented on make.sh
> +)
I just realized you like using `()`... it's really atypical. Use braces instead. And also, `if (( ${#} > 0 ))`.

2024-11-06 19:06 UTC, gcarreno commented
Hey Artem(@theavege),

While I do appreciate, A LOT, what you're trying to do with all the `PR`s you've been making, I do have to ask why are you trying your methods, when you can just use [setup-lazarus](https://github.com/gcarreno/setup-lazarus)

The other thing that kinda bothers me is the fact that I'm the author of `setup-lazarus` and I chose not to use `CI`/`CD` on this repo. I could have, but I chose not to.

My last remark would be: Please learn how to use `matrix` on the GitHub workflows. And also learn how to upload the compiled binaries. The stuff you've been doing can't even be classified as neither Continuous Integration(There are no unit tests) nor Continuous Delivery(You don't even have a path for a release)

Nonetheless, I will thank you for your effort, but I'll have to close this `PR`.

Cheers,
Gus

2024-11-06 19:06 UTC, closed without merging

2024-11-07 13:02 UTC, theavege commented
// While I do appreciate, A LOT, what you're trying to do with all the PRs you've been making, I do have to ask
//why are you trying your methods, when you can just use [setup-lazarus](https://github.com/gcarreno/setup-lazarus)

I hope you will spread your solution.

Thanks for the feedback! I'll take it on board.

2024-11-08 06:07 UTC, gcarreno commented
Hey Artem(@theavege),

I asked a friend to have a look at `setup-lazarus` and he's doing a full rewrite.
After that I'll see what I can do.

Cheers,
Gus